disabled_rules:
    - line_length
    - type_name
    - function_body_length
    - shorthand_operator
    - final_class
    - trailing_whitespace

opt_in_rules:
    - empty_count
    - empty_string
    - empty_xctest_method
    - private_action
    - private_outlet
    - closure_end_indentation
    - closure_spacing
    - operator_usage_whitespace
    - overridden_super_call
    - explicit_init
    - fatal_error_message
    - force_unwrapping

excluded:
  - /Youla/Pods 
  - Pods
  - Youla/HFSwipeView
  - vendor

line_length:
  - 150
  - 200

file_length:
  warning: 500
  error: 1200

type_body_length:
  - 300 # warning
  - 400 # error

cyclomatic_complexity:
    warning: 18
    error: 28

identifier_name:
    max_length:
        warning: 40
        error: 60
    min_length:
        warning: 3
        error: 2

identifier_name:
  excluded: # excluded via string array
    - id
    - GlobalAPIKey
    - vc
    - i
    - j
    - k
    - m
    - w
    - h
    - r
    - g
    - b
    - a
    - res
    - url
    - err
    - ds
    - at

nesting:
  type_level:
    warning: 2
  statement_level:
    warning: 5

custom_rules:
    zero:
        name: "Short .zero"
        regex: '\(top: 0, left: 0, bottom: 0, right: 0\)'
        message: "Please use short init `.zero`."
        severity: error

    marks_style:
        name: "Mark Style"
        regex: '// MARK:(?!\s-\s\w+?)'
        message: "Marks should follow the following structure: `// MARK: - Topic`."
        severity: warning

    unowned_usage:
        name: "Unowned in Capture List"
        regex: '(?<=\{\s\[)(?:[\w\s\,]*?)unowned(?=[^\]]*?\])'
        message: "Use _weak_ keyword if you're not sure about property lifetime."
        severity: warning
